name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: output

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      # ✅ Add this step here before uploading artifacts
      - name: Create dist directory if not exists
        run: mkdir -p dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist

      - name: Set up Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add -A
          git commit -m "Updated contribution snake animation" || exit 0
          git push
